### PR TITLE
fixed filename metadata bug when using file and file_filename

### PR DESCRIPTION
**Pull request by ChrisPappalardo**
addresses #1000

### CODE REVIEW

**Comment by six5532one** [comment]
Thanks @ChrisPappalardo ! Would you mind adding a test, perhaps using a test case similar to the code snippet in https://github.com/Unstructured-IO/unstructured/issues/1000#issue-1829359752?

**Comment by ChrisPappalardo** [comment]
Latest will fix failing tests and changelog check, but not sure what to do about:  https://github.com/Unstructured-IO/unstructured/actions/runs/5727711571/job/15520848419?pr=1002

**Comment by qued** [comment]
@ChrisPappalardo The remaining test failures are non-blocking as far as I'm concerned. Could you make one last change and move the description of the change in the changelog up to the latest revision, and increment the dev revision number (i.e. from `dev0` to `dev1` as things stand now)?

**Comment by ChrisPappalardo** [comment]
> @ChrisPappalardo The remaining test failures are non-blocking as far as I'm concerned. Could you make one last change and move the description of the change in the changelog up to the latest revision, and increment the dev revision number (i.e. from `dev0` to `dev1` as things stand now)?

Done

**Review by qued — APPROVED** [review]
LGTM! Thanks for the contribution @ChrisPappalardo !

**Comment by qued** [comment]
Oops, I neglected to say the version also needs to be changed in __version__.py. Could you update that as well @ChrisPappalardo , and then we should be good to merge.

**Comment by ChrisPappalardo** [comment]
> Oops, I neglected to say the version also needs to be changed in **version**.py. Could you update that as well @ChrisPappalardo , and then we should be good to merge.

Done!

**Pull request merged**
