### PR TITLE
build(deps): bump version for security patches

### PR DESCRIPTION
**Pull request by MthwRobinson**
### Summary

Bumps dependency versions to apply security patches flagged by dependabot. Also adds the following constraint to fix a dependency resolution conflict resulting from a pin in `langchain-community`.

```
packaging<24.0
packaging>=23.2
```

### CODE REVIEW

**Comment by MthwRobinson** [comment]
@awalker4 - Have a few tests failing in here with the following. Tried pinning the client version but looks like it's still broken. Any idea what might be causing that? Seemed to me like it could be a change in the client SDK interface.

```
FAILED test_unstructured/partition/test_api.py::test_partition_via_api_custom_url - AttributeError: 'RetryConfig' object has no attribute 'config'
FAILED test_unstructured/partition/test_api.py::test_partition_via_api_pass_list_type_parameters - unstructured_client.models.errors.sdkerror.SDKError: API error occurred: Status 401
{"detail":"API key is missing, please provide an API key in the header."}
= 2 failed, 2017 passed, 13 skipped, 2 deselected, 3 xfailed, 9 xpassed, 6 warnings in 1954.31s (0:32:34) =
```

**Comment by awalker4** [comment]
A few users have hit the RetryConfig error as well - let me take a look.

**Review by ahmetmeleq — APPROVED** [review]
Can verify the langchain error with `make pip-compile`. Other change in the PR is `make pip-compile`, LGTM

**Comment by MthwRobinson** [comment]
@ahmetmeleq - Still getting the retry config error in CI, but sounds like @awalker4 is taking a look at that

**Pull request closed without merging**
