### PR TITLE
First pass at Astra Doc Ingest logic

### PR DESCRIPTION
**Pull request by erichare**
@potter-potter i don't have write access to your branch, so opened up a PR for my changes here

### CODE REVIEW

**Comment by potter-potter** [comment]
@erichare Let's continue working on this from here.

Is this running successfully for you when you test it?

**Comment by erichare** [comment]
@potter-potter i had something come up earlier and haven't had a chance to fully test, i will get back to you on that soon. Also sorry for the very undescriptive branch name here haha, I forgot to change the default 😄 

I'll follow up soon

**Comment by potter-potter** [comment]
I don't think we can fully sort of copy delta-table. I was just trying to point you to something that read from a "database table"-like source. There isn't really a good example of a source connector that parallels AstraDB as far as I can tell.

**Comment by potter-potter** [comment]
It actually looks like this gets the entire table:
astra_docs = list(self.astra_db_collection.paginated_find())

In most of the connectors, since they are not table based, `get_ingest_docs` just gets a pointer to the docs and then we can potentially fan out downloaders to download the docs with `get_files`

That being said, this is not a "docs" based connector (its table based) so it is a little different. I will look through our source connectors again to see if there is a better connector to model.

**Comment by erichare** [comment]
> It actually looks like this gets the entire table: astra_docs = list(self.astra_db_collection.paginated_find())
> 
> In most of the connectors, since they are not table based, `get_ingest_docs` just gets a pointer to the docs and then we can potentially fan out downloaders to download the docs with `get_files`
> 
> That being said, this is not a "docs" based connector (its table based) so it is a little different. I will look through our source connectors again to see if there is a better connector to model.

That is a really great point. Yep, it will pull the full table. paginated_find itself can take a filter condition, if there's any way to pass kwargs to `get_ingest_docs`?

**Comment by MthwRobinson** [comment]
@potter-potter - Do you know if this PR is still being actively worked?

**Comment by erichare** [comment]
@MthwRobinson I got pulled into some other stuff, but would like to get this merged... with that said, we sort of had two simultaneous PRs going, and i think this particular PR is out of date. If @potter-potter agrees, i'll open a new PR with just the Astra DB Source connector logic and we can close this one. I have some updates to make to it anyway as a result of recent changes on the Astra end.

**Comment by MthwRobinson** [comment]
Thanks @erichare !

**Comment by potter-potter** [comment]
@erichare Thanks. If you could close this and open a new one. We merged in the updates to the Astra destination, but this source one needed more work.

**Comment by erichare** [comment]
> @erichare Thanks. If you could close this and open a new one. We merged in the updates to the Astra destination (via a different PR), but this source connector needed more work.

I'm on it @potter-potter . Thanks!

**Pull request closed without merging**
