### PR TITLE
chore: Fix parse received data

### PR DESCRIPTION
**Pull request by mallorih**
The `_parse_received_data` function current returns `None` when the `datetimestamp` variable is set. This PR fixes this bug.

### CODE REVIEW

**Comment by mallorih** [comment]
Weird, I accidentally reverted the change.

**Review by MthwRobinson — CHANGES_REQUESTED** [review]
Changes look could, could you add a test too?

**Comment by mallorih** [comment]
@MthwRobinson I changed my fix in the Name class in `email_elements` a little and added the test.

**Review by MthwRobinson — APPROVED** [review]
LGTM!

**Pull request merged**
