### PR TITLE
fix: initialize uri before try-except

### PR DESCRIPTION
**Pull request by Klaijan**
Fix github issue https://github.com/Unstructured-IO/unstructured/issues/1686

### CODE REVIEW

**Comment by cragwolfe** [comment]
worth an unstructured and unstructured-api release?

**Comment by Klaijan** [comment]
I don't think it's a big issue considering sentry just bumped into it just now. It's a quick fix that's already done, but definitely can wait.

**Comment by awalker4** [comment]
For context, we've had 2 users hit this across 14 documents. Certainly not the highest impact just yet.

**Review by awalker4 — APPROVED** [review]
LGTM!

**Pull request merged**
