### PR TITLE
fix: `page_number` should not always be equal to 1 in the metadata

### LINKED ISSUE #650: bug/page number is 1 for all pages when using the "fast" strategy
[sample.pdf](https://github.com/Unstructured-IO/unstructured/files/11600701/sample.pdf)
**Describe the bug**
For `unstructured>=0.6.9`, the page number if 1 in the metadata when using the `"fast"` strategy with `partition_pdf`, even for elements that do not come from the first page.

**To Reproduce**
```python
from unstructured.partition.pdf import partition_pdf

filename = "sample.pdf"
elements = partition_pdf(filename=filename, strategy="fast")
# All the page numbers are 1
[el.metadata.page_number for el in elements]
```

**Expected behavior**
The page number should reflect that actual page number the element came from.

**Desktop (please complete the following information):**
 - `unstructured>=0.6.9`

**Additional context**
- This worked correctly up until at least `0.6.6`

### PR DESCRIPTION
**Pull request by MthwRobinson**
### Summary

Closes #650. Resolves an issue in `_add_element_metadata` that caused all elements to have `page_number=1` in the metadata, regardless of the page the element originated from.

### Testing

```python
from unstructured.partition.pdf import partition_pdf

filename = "example-docs/layout-parser-paper-fast.pdf"
elements = partition_pdf(filename=filename, strategy="fast")
elements[-1].metadata.page_number
```

### CODE REVIEW

**Review by qued — COMMENTED** [review]
The page numbers aren't coming out right for me in the test code: 
image
Is this dependent on a new `unstructured-inference` version? I have 0.4.4 in my test environment.

**Comment by MthwRobinson** [comment]
This is independent of the `unstructured-inference` version. Those page numbers look right to me though. I get the same:

```python
In [15]: elements[13].text
Out[15]: 'Deep Learning(DL)-based approaches are the state-of-the-art for a wide range of document image analysis (DIA) tasks including document image classiﬁcation [11,'

In [16]: elements[13].metadata.page_number
Out[16]: 1

In [17]: elements[14].text
Out[17]: '2'

In [18]: elements[14].metadata.page_number
Out[18]: 2

In [19]: elements[15].text
Out[19]: 'Z. Shen et al.'

In [20]: elements[15].metadata.page_number
Out[20]: 2

In [21]: elements[16].text
Out[21]: '37], layout detection [38, 22], table detection [26], and scene text detection [4]. A generalized learning-based framework dramatically reduces the need for the manual speciﬁcation of complicated rules, which is the status quo with traditional methods. DL has the potential to transform DIA pipelines and beneﬁt a broad spectrum of large-scale document digitization projects.'

In [22]: elements[16].metadata.page_number
```

And that looks like it matches with the page transition in the document:

image

**Comment by qued** [comment]
Ohhh for some reason my mind decided each element was a page.

**Review by qued — APPROVED** [review]
LGTM!

**Pull request merged**
