### PR TITLE
refactor: For S3 Ingest, write to file directly using `json.dump`

### PR DESCRIPTION
**Pull request by tomaarsen**
Hello!

## Pull Request overview
* Use `json.dump(..., file)` rather than `file.write(json.dumps(...))`.

## Details
Rather than writing to string in memory first, and then writing to file, this PR proposes to write to file directly using `json.dump`.

### References:
* [`json.dump`](https://docs.python.org/3/library/json.html#json.dump)
* [`json.dumps`](https://docs.python.org/3/library/json.html#json.dumps)

Personally, I always remember the difference as "dumps => dump string" (and idem for "loads => load string").

- Tom Aarsen

### CODE REVIEW

**Review by cragwolfe — APPROVED** [review]
LGTM!

**Comment by tomaarsen** [comment]
I think all this needs is for the changelog (and __version__) version to be bumped. I can tackle this tomorrow if it hasn't been done by then.

**Comment by cragwolfe** [comment]
@tomaarsen , I would have added the CHANGELOG / version change but don't think I can push to your branch.

**Comment by tomaarsen** [comment]
You can't? Perhaps some of my settings are messed up.
No worries, though. I'll tackle it.

**Pull request merged**
