### PR TITLE
bugfix: ingest pipeline with chunking and embedding does not persist data to the embedding step

### PR DESCRIPTION
**Pull request by ahmetmeleq**
Closes: #1892 (check the issue for more info)

### CODE REVIEW

**Comment by ahmetmeleq** [comment]
https://github.com/Unstructured-IO/unstructured/pull/1774 will be testing this problem with its ingest test

**Review by ryannikolaidis — COMMENTED** [review]
assuming this will effectively be covered once we have an end to end ingest test that includes embedding+chunking in CI?

**Review by ryannikolaidis — APPROVED** [review]

**Comment by ahmetmeleq** [comment]
exactly, https://github.com/Unstructured-IO/unstructured/pull/1774 will be testing this problem with its ingest test

**Comment by ryannikolaidis** [comment]
maybe bump the pr title to be a bit more specific? (also pr title will be the title of the commit in main)

**Comment by ahmetmeleq** [comment]
> maybe bump the pr title to be a bit more specific? (also pr title will be the title of the commit in main)

Agreed, updated now 👍

**Comment by ahmetmeleq** [comment]
Removing `test-ingest-sharepoint.sh` from `test-ingest.sh` until https://github.com/Unstructured-IO/unstructured/pull/1894 merges with its test fixture updates.

(Details: Sharepoint tests fail right now due to our updates to some documents in the Sharepoint platform. We did those updates to test for permissions opt-in functionality in https://github.com/Unstructured-IO/unstructured/pull/1894 )

**Pull request merged**
