### PR TITLE
Favor upsert over add + use element_id to prevent duplicates

### PR DESCRIPTION
**Pull request by 0xjgv**
Make chroma ingest pipeline idempotent :)
@potter-potter

### CODE REVIEW

**Comment by potter-potter** [comment]
@0xjgv Thanks for this! And thanks for alerting me. Great idea.

I will bring it up to the team.

**Comment by potter-potter** [comment]
@ahmetmeleq @0xjgv can you see any downsides to doing it this way? (seems like it is a good idea all aound)

**Comment by potter-potter** [comment]
@ryannikolaidis Think this change will affect any users of ChromaDB that expect duplicates? (not sure why they would want duplicates....)

**Comment by ryannikolaidis** [comment]
> @ryannikolaidis Think this change will affect any users of ChromaDB that expect duplicates? (not sure why they would want duplicates....)

with matching ids? I think that's okay

**Comment by 0xjgv** [comment]
> @ahmetmeleq @0xjgv can you see any downsides to doing it this way? (seems like it is a good idea all around)

🤔 I can't think of any downsides though. Collisions are not very likely and there are no clear advantages to allowing duplicates in the DB. Idepomtecy reduces storage space, increases query performance, and simplifies data maintenance and integrity.

**Comment by potter-potter** [comment]
@0xjgv Thanks for this! I am putting it into a small pr with one other small update so that it runs through our CI/CD.

https://github.com/Unstructured-IO/unstructured/pull/3086

**Comment by 0xjgv** [comment]
Implemented in https://github.com/Unstructured-IO/unstructured/pull/3086

**Pull request closed without merging**
