### PR TITLE
chore: add py.typed

### PR DESCRIPTION
**Pull request by Goldziher**
This PR adds `py.typed`, which will fix issues of the following type:

### CODE REVIEW

**Comment by MthwRobinson** [comment]
Thanks for this @Goldziher !

**Review by MthwRobinson — APPROVED** [review]
LGTM

**Comment by MthwRobinson** [comment]
@Goldziher - Could you add an entry to the changelog? Should be good to go once that's in.

**Comment by Goldziher** [comment]
> @Goldziher - Could you add an entry to the changelog? Should be good to go once that's in.

Done!

**Pull request merged**
