### PR TITLE
docs: update capabilities table; fix mistake in para grouping docs

### LINKED ISSUE #679: A small mistake in the documentation
In [group_broken_paragraph](https://unstructured-io.github.io/unstructured/bricks.html#group-broken-paragraphs) section of the documentation, `para_split_re = re.compile(r"(\s*\n\s*){3}")` was used to change the behavior of the function `group_broken_paragraphs` using `paragraph_split` kwarg. While it seems like it should be `para_split_re = re.compile(r"(\s*\nn\\s*){3}")` instead.

### PR DESCRIPTION
**Pull request by MthwRobinson**
### Summary

Updating the capabilities based on testing @christinestraub did as part of #516 . Also closes #679 and fixes a small doc mistake.

### CODE REVIEW

**Comment by qued** [comment]
I don't understand this change. The example code works without the change and doesn't work with the change.

**Comment by qued** [comment]
> I don't understand this change. The example code works without the change and doesn't work with the change.

Referring to the change in `bricks.rst`. The changes to the readme look good.

**Comment by MthwRobinson** [comment]
@qued - Thanks yeah I'll revert the `bricks.rst` change. That was mentioned in the linked issue, but seems like the original docs were correct after all.

**Review by qued — APPROVED** [review]
LGTM pending the reversion of the bricks doc change!

**Review by qued — APPROVED** [review]
LGTM pending the reversion of the bricks doc change!

**Pull request merged**
