### PR TITLE
Fix: Add timeout to partition html

### PR DESCRIPTION
**Pull request by pratiksinghchauhan**
This PR adds a timeout parameter to requests in partition_html to stop the code from blocking indefinitely  if the URL fails to respond withing the given timeout,

### CODE REVIEW

**Comment by badGarnet** [comment]
Hi @pratiksinghchauhan thanks for the contribution. Could you please add a line to `CHANGELOG.md` under "Fixes" to describe what this change does? And per standard please increase the dev number for the version number?

**Comment by pratiksinghchauhan** [comment]
@badGarnet! I will make the changes and update the PR. Thanks!

**Comment by MthwRobinson** [comment]
@pratiksinghchauhan - Is this something you'd still like to work on?

**Comment by pratiksinghchauhan** [comment]
@MthwRobinson Apologies for the delay! I am still interested in getting this done. I have already completed the feature set just need to get the documentation done. I will get it done this weekend for sure.

**Comment by MthwRobinson** [comment]
Sounds good - thanks!

**Comment by pratiksinghchauhan** [comment]
@MthwRobinson I have updated the PR. Do let me know.

**Pull request closed without merging**
