### PR TITLE
add support for `start_index` in `html` links extraction

### LINKED ISSUE #2625: enhancement: add support for `start_index` in `html` links extraction
**Is your feature request related to a problem? Please describe.**
Currently, `parition_html` supports link_text and link_url but not the `link_start_index`.
```
"metadata": {
   ...
    "link_texts": [
        "International"
    ],
    "link_urls": [
        "https://www.weather.gov/wrn/wrns"
    ],
    ...
}
```
**Describe the solution you'd like**
- determine `html` links `start_index` within a tag
- add `link_start_indexes` metadata field

**Describe alternatives you've considered**

**Additional context**
html links extraction tests will need to be updated to check all link-related metadata fields.

### PR DESCRIPTION
**Pull request by MiXiBo**
add support for start_index in html links extraction (closes #2625)

Testing
```
from unstructured.partition.html import partition_html
from unstructured.staging.base import elements_to_json


html_text = """<html>
        <p>Hello there I am a <a href="/link">very important link!</a></p>
        <p>Here is a list of my favorite things</p>
        <ul>
            <li><a href="https://en.wikipedia.org/wiki/Parrot">Parrots</a></li>
            <li>Dogs</li>
        </ul>
        <a href="/loner">A lone link!</a>
    </html>"""

elements = partition_html(text=html_text)
print(elements_to_json(elements))
```

### CODE REVIEW

**Comment by MiXiBo** [comment]
Is it ok if we merge that into main?

**Comment by christinestraub** [comment]
@MiXiBo Is this the same PR as PR #2537?

**Comment by MiXiBo** [comment]
@christinestraub I also fixed #2600

**Review by MthwRobinson — APPROVED** [review]
@christinestraub - This is good to go from my perspective once tests are passing!

**Comment by MiXiBo** [comment]
Thanks for looking into that and adding the tests. Can we support you somehow with that?

**Comment by christinestraub** [comment]
> Can we support you somehow with that?

Thank you! We'll get back to you if we need your support.

**Comment by DanielRoeder1** [comment]
If I understand this feature correctly then the start_index does not seem to be accurate.

Here a minimal example:

```
from unstructured.partition.html import partition_html
# A random cnn article
url = "https://edition.cnn.com/2024/03/18/world/haiti-crisis-militias-battle-intl-latam/index.html"
elements = partition_html(url = url)
for elem in elements:
  if elem.links:
    sel_link = elem.links[0]
    idx_text = elem.text[sel_link["start_index"]:]
    print(f"Link text: {sel_link['text']}")
    print(f"Elem text: {idx_text}")
    print(f"Idx match: {idx_text.startswith(sel_link['text'])}")
    print("#####")
```

If the feature would work correctly then the elem.text[link_start_index:] should be the beginning of the link phrase?

**Comment by christinestraub** [comment]
Hi @DanielRoeder1
Thanks for your flagging! The start_index  was inaccurate if an element's text contained leading extra whitespace. I fixed the issue and now the `elem.text[link_start_index:]` should be the beginning of the link phrase, except when `start_index` is -1.

**Comment by MiXiBo** [comment]
is there still an issue?

**Comment by christinestraub** [comment]
In some cases, the `start_index` calculation was found to be inaccurate. Can you please check the `start_index` calculation  in the actual html files? I attached the html file taht I tested.
[spring-weather.zip](https://github.com/Unstructured-IO/unstructured/files/14747888/spring-weather.zip)

**Comment by MiXiBo** [comment]
Thanks @christinestraub,

the test file was exactly was I was looking for. Will work on that today.

**Comment by MiXiBo** [comment]
@DanielRoeder1  Thanks for the great helper tool!

I used it with the sample document:

```
from unstructured.partition.html import partition_html
url = "https://www.weather.gov/news/230303-spring-safety"
elements = partition_html(url = url, mode="elements", strategy="fast")
count_true = 0
count_false = 0
wrong_elements = []
for elem in elements:
  if elem.links:
    sel_link = elem.links[0]
    idx_text = elem.text[sel_link["start_index"]:]
    print(f"Link text: '{sel_link['text']}'")
    print(f"Elem text: '{idx_text}'")
    print(f"Idx match: {idx_text.startswith(sel_link['text'])}")
    print("#####")
    if idx_text.startswith(sel_link['text']):
      count_true = count_true + 1
    else:
      count_false = count_false + 1

print("True: ", count_true)
print("False: ", count_false)
```

@christinestraub is it possible that the json evaluation is wrong?

When we read the document, then the element text starts with 'Weather Safety' hence the index would be 0 in my opinion and not 52, see: https://github.com/Unstructured-IO/unstructured/blob/fcee08afd91ab4e54f8a258d073969722ef78343/test_unstructured_ingest/expected-structured-output/azure/spring-weather.html.json#L148 


Screenshot 2024-03-27 at 13 55 09




and I probably messed up a little as it was before:

links.append({"text": tag_elem.text, "url": href, "start_index": -1})

which I changed to:
links.append({"text": tag_elem.text, "url": href, "start_index": 0})

as I don't really understand why index -1 is used when the first character starts at 0

when I have it at 0 then @DanielRoeder1  sample tool runs through

**Comment by DanielRoeder1** [comment]
Happy to see that I could contribute a bit!

I am currently still running into issues when the text of a link is nested within another tag. 

Example:
<a href= ...><h3>Some text</h3></a>.

 This does appear on some websites I am working with.

In this case the tag.text returns None, and tag.tail also provides None which results in the start_index being incorrect.

**Comment by christinestraub** [comment]
> @christinestraub is it possible that the json evaluation is wrong?

> When we read the document, then the element text starts with 'Weather Safety' hence the index would be 0 in my opinion and not 52, see:

yes, it's possible that the json evaluation is wrong and it can be updated through CI

**Comment by christinestraub** [comment]
start_index: -1` means that the link is to the root of the element, that is, `element.tag is "a"`. For example, in the sample document, the element whose text is "U.S. Department of Commerce".  On the other hand, `start_index: 0` means that the link is not the root of the element and is the first child of the element. that is, `element.tag is NOT "a"`. For example, an element whose text begins with "Weather Safety..." (the element in the above screenshot you attached).

**Comment by MiXiBo** [comment]
@christinestraub   start_index is set back to -1 for root elements.

@DanielRoeder1 I tuned one line from your code into:
```
start_index = sel_link["start_index"] if sel_link["start_index"] >= 0 else 0
idx_text = elem.text[start_index:]
```
so that the tests can run through.


I tested for tags surrounded by href, see sample html:

```
<!DOCTYPE html>
<html>
  <body>
    <a href="http://example.com"><h3>H3</h3> Link <h2>H2</h2></a>
  </body>
</html>

```

**Comment by christinestraub** [comment]
image

@MiXiBo Did you get a chance to check `start_index` for `elements[5]`?
```
elements[5].text[14:]
elements[5].text[25:]
elements[5].text[38:]
elements[5].text[42:]
...
```

**Comment by MiXiBo** [comment]
> image
> 
> @MiXiBo Did you get a chance to check `start_indexes` for `elements[5]`?
> 
> ```
> elements[5].text[14:]
> elements[5].text[25:]
> elements[5].text[38:]
> elements[5].text[42:]
> ...
> ```

wait, I didn't count them before. Sorry for that. Afaik it was still just 24 .. and the document got 100. Will have a look on Tuesday again.

**Comment by MiXiBo** [comment]
@christinestraub I did looked into it and I tried to make it working. However, I did pause it for now as I do believe that the text delivered for the element is wrong. Look at the image. When there is a nested list <ul> then the following <li> elements are not clean parsed. In that case they do include line breaks and spaces. The start_index expects to have it clean like with a not nested list. The question is how you want to process. I would suggest to improve the nested list handling. See screenshots

nested list. parsed text contains many whitespaces and also line breaks

Screenshot 2024-04-03 at 17 44 21

Screenshot 2024-04-03 at 17 49 40


regular list


Screenshot 2024-04-03 at 17 56 57



Screenshot 2024-04-03 at 17 47 36

**Comment by christinestraub** [comment]
Yes, start_index does not work correctly when nested list <ul>, <li> elements include line breaks and spaces. Let's pause it for now. @MiXiBo

**Review by cragwolfe — APPROVED** [review]

**Review by christinestraub — APPROVED** [review]
TODO: start_index does not work correctly in some corner cases where nested list (<ul>, <li>) elements include whitespaces and line breaks.

**Comment by christinestraub** [comment]
Finally merged this PR, thank you for your contribution! @MiXiBo

**Comment by MiXiBo** [comment]
Thanks you so much!

**Pull request merged**
