### PR TITLE
Klaijan/test json partition

### PR DESCRIPTION
**Pull request by Klaijan**
Update `test_json` to not use auto partition.
Update other test files to check its invariant with `elements_to_json`.

### CODE REVIEW

**Review by cragwolfe — APPROVED** [review]

**Comment by cragwolfe** [comment]
@Klaijan , it looks like https://github.com/Unstructured-IO/unstructured/pull/1163 introduced a real bug with respect to test_partition_pdf_with_json[ocr_only]. If you verify that is the case, feel free to skip testing ocr_only for this particular test, and create a github issue to track the bug.

**Comment by Klaijan** [comment]
Note: `ocr_only` strategy returned different datatype makes assertion failed.

**Comment by Klaijan** [comment]
blocked by #1219

**Comment by Klaijan** [comment]
Found `nan` bug in coords.

**Pull request merged**
