### PR TITLE
update constraints to pin weaviate during ci

### PR DESCRIPTION
**Pull request by badGarnet**
This PR ensures the version for `weaviate` is consistent in CI testing. Latest (3.24.1) is not compatible with our test needs and last version that run successfully in CI is 3.23.2.

### CODE REVIEW

**Review by cragwolfe — APPROVED** [review]
🙏 🙏

**Comment by qued** [comment]
I'm not sure pinning is the solution here. I get the impression they are permanently removing client-side schema validation, so it's no good hanging on to a test on our side that depends on that.

**Comment by badGarnet** [comment]
> I'm not sure pinning is the solution here. I get the impression they are permanently removing client-side schema validation, so it's no good hanging on to a test on our side that depends on that.

wait, does the validation actually sends data to some server somewhere?

**Comment by qued** [comment]
I'll reiterate I think it's better to skip/remove the test than pin to a version of Weaviate that can potentially fall behind. I don't think it does us any good, for example, to validate a schema against a validation check that's out of date. (And if it's not out of date, then our schema is still valid whether we are testing it or not.)

That being said, this needs to go through so other PRs aren't blocked, so I'm not going to hold things up.

**Pull request merged**
