### PR TITLE
Unstructured Dev Container / Codespace

### PR DESCRIPTION
**Pull request by crosleythomas**
Opening this as a draft PR to see if having dev containers / codespaces for Unstructured would be of interest.

Especially with the Data Connector Blitz, this would be a useful way to get new contributors up and running easily on the project.

I have tested the code below on my local VS Code setup and will test it in the codespace with the opening of this PR.

### CODE REVIEW

**Comment by cragwolfe** [comment]
Hi @crosleythomas ! I just wanted to give you a quick heads up that getting all the OS deps in an image can be tricky.
See https://github.com/Unstructured-IO/unstructured/blob/main/scripts/setup_ubuntu.sh for a script that does that handles that for ubuntu.
And this gist that leverages that script in a `docker run ubuntu` container
 https://gist.github.com/cragwolfe/e230fea5491ce2704356ee17857ee73c .
 
 We'll have supported Dockerfile's coming soon!

**Comment by crosleythomas** [comment]
> Hi @crosleythomas ! I just wanted to give you a quick heads up that getting all the OS deps in an image can be tricky. See https://github.com/Unstructured-IO/unstructured/blob/main/scripts/setup_ubuntu.sh for a script that does that handles that for ubuntu. And this gist that leverages that script in a `docker run ubuntu` container https://gist.github.com/cragwolfe/e230fea5491ce2704356ee17857ee73c .
> 
> We'll have supported Dockerfile's coming soon!

@cragwolfe perfect! If you have an officially supported docker image then the devcontainer config piece will be even easier. Do you have an issue I can track to see when the image is available and then I'll revisit this PR to reference your image?

**Comment by cragwolfe** [comment]
> @cragwolfe perfect! If you have an officially supported docker image then the devcontainer config piece will be even easier. Do you have an issue I can track to see when the image is available and then I'll revisit this PR to reference your image?

Yes, thanks for asking. here it is: https://github.com/Unstructured-IO/unstructured/issues/295

**Comment by MthwRobinson** [comment]
Closing this one since there hasn't been activity in a few months, but feel free to reopen if this is still in progress.

**Pull request closed without merging**
