### PR TITLE
Refactor threshold to annotation_threshold and make it an optional parameter

### PR DESCRIPTION
**Pull request by MiXiBo**
We are activating to configure the annotation threshold for links as an optional parameter. 

The reason for the change is that we ran into issues extracting simple text links from PDF documents that were created with MS Word. The sample PDF from unstructured worked with a default value of 0.9, and the PDF generated with Word resulted in a threshold of approx 0.67.

We do use unstructured in together with langchain within an automated container deployment and to access by default the setting 'annotation_threshold' (refactored from 'threshold') can be very helpful.

### CODE REVIEW

**Comment by sjoerd222888** [comment]
This is to address the issue [#2482](https://github.com/Unstructured-IO/unstructured/issues/2482).

@christinestraub you have assigned yourself to that issue, what do you think about the proposed solution?

**Comment by sjoerd222888** [comment]
What can we do to get the workflows approval? What must we do for the changelog for example?

**Comment by christinestraub** [comment]
> What can we do to get the workflows approval? What must we do for the changelog for example?

Can you add the following lines to `Enhancements` section in the changelog.md?
```
### Enhancements

* **add support for `start_index` in `html` links extraction**
* **improve embedded links extraction in `partition_pdf()` for `fast` strategy**
```

**Review by christinestraub — CHANGES_REQUESTED** [review]
Can you please revert the changes related to support for start_index in html links extraction and use PR #2600 for those changes?

**Comment by MiXiBo** [comment]
> Can you please revert the changes related to support for start_index in html links extraction and use PR #2600 for those changes?

yes, I will prepare it. Thanks

**Comment by MiXiBo** [comment]
> Can you please revert the changes related to support for start_index in html links extraction and use PR #2600 for those changes?

done

**Review by christinestraub — APPROVED** [review]
LGTM! We're considering to configure the `annotation_threshold` using an [environment variable](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/utils/config.py) (e.g. `UNSTRUCTURED_PDF_ANNOTATION_THRESHOLD`) after this PR is merged. We'll update you once we make the change.

**Pull request merged**
