### PR TITLE
fix: chunking fails with detection_class_prob in metadata

### PR DESCRIPTION
**Pull request by ryannikolaidis**
Fixes chunking when `detection_class_prob` appears in Element metadata.

Currently, when `detection_class_prob` appears in Element metadata, Elements will only be combined by `chunk_by_title` if they have the same `detection_class_prob` value (which is rare). This is unlikely a case we ever need to support and most often results in no chunking. 

`detection_class_prob` is now included in the chunking list of metadata keys excluded for similarity comparison. 

## Testing

Unit test added that currently breaks due to changes in to `detection_class_prob` but with this change passes since `detection_class_prob` is excluded from chunking similarity comparison.

### CODE REVIEW

**Comment by qued** [comment]
So the current logic is to start a new section when any metadata field changes? This makes sense for page numbers, and maybe 1 or 2 fields that I can't think of right now, but is this something we should whitelist rather than blacklist? It seems more likely we would _not_ want this behavior for most new metadata fields.

**Review by qued — APPROVED** [review]
LGTM for a quick fix, but per my comment I think at some point we should switch to whitelisting metadata fields we want to use to trigger new chunks rather than blacklisting ones we don't, to prevent this happening in the future when we add new fields.

**Comment by cragwolfe** [comment]
Related: https://github.com/Unstructured-IO/unstructured/issues/1286 .
IMO, inverse operations of composite elements to get the original will be important. one could "re-index" without saving things twice, for instance, or get high granularity detail about any sub-element in a downstream app.

**Review by newelh — APPROVED** [review]

**Comment by ryannikolaidis** [comment]
yes, totally agree on both of these points (whitelist and inverse operations of composite elements). just a quick fix here so that chunking still works out of the box when inference is used (triggering detection_class_prob)

**Comment by ryannikolaidis** [comment]
hopefully test coverage still keeps us honest with those changes.

**Pull request merged**
