### PR TITLE
add read and combine json

### PR DESCRIPTION
**Pull request by preemware**
For review.

### CODE REVIEW

**Comment by ron-unstructured** [comment]
`read_and_combine_json` function is used in the "Multi-files API Processing" example in the [documentation](https://unstructured-io.github.io/unstructured/examples/dict_to_elements.html#step-5-combine-json-files-from-multi-files-ingestion)

**Comment by preemware** [comment]
I made a mistake. I believe the intend of the function was to return as a `Iterable[dict[str, Any]]`. I can make this change.

**Comment by preemware** [comment]
Referencing the original documentation. The intent appears to have it return as `Iterable[dict[str, Any]]` into `dict_to_elements`. If it returned a list, the code wouldn't work as intended.

```
combined_json_data = read_and_combine_json("Connector-Output/world-development-bank-2023")
elements = dict_to_elements(combined_json_data)
chunks = chunk_by_title(elements)
```

**Review by ron-unstructured — APPROVED** [review]
LGTM

**Comment by MthwRobinson** [comment]
@preemware - Are you still working on this?

**Pull request closed without merging**
