### PR TITLE
added parent_element as output for overlapping cases

### PR DESCRIPTION
**Pull request by erjieyong**
To provide more utility to the `catch_overlapping_and_nested_bboxes` and `identify_overlapping_or_nesting_case` functions, included parent_element as part of the output. 

This would allow user to 
- identify the parent element in the overlapping case: `nested {type*} in {type*}`. Currently, if the element types is similar, an example case output would be `nested Image in Image` which is confusing. 
- easily identify elements to keep or delete

### CODE REVIEW

**Comment by erjieyong** [comment]
have added test cases to `test_utils.py`

**Comment by erjieyong** [comment]
@christinestraub , please let me know if there's any changes needed on my end to get this merged. I am quite new to this, so appreciate your guidance.

**Comment by christinestraub** [comment]
@erjieyong Can you please fix the changelog conflicts?

**Review by christinestraub — APPROVED** [review]
Note: some of the CI requires unstructured secrets to run and they all passed in this cloned branch - https://github.com/Unstructured-IO/unstructured/pull/2548

**Pull request merged**
