### PR TITLE
Update paddle_ocr.py

### PR DESCRIPTION
**Pull request by l4b4r4b4b4**
Use latest paddleocr lib & OCR model

### CODE REVIEW

**Comment by qued** [comment]
Hi @l4b4r4b4b4, we can't use `paddleocr` directly as they are dependent on a package (PyMuPDF) that has a non-compatible license.

**Comment by l4b4r4b4b4** [comment]
@qued so that means it would still be possible to either
1. Bump unstructured_paddleocr without PyMuPDF
2. Or even just pass the latest model as ocr_version param 
To use latest PaddleOCR model in unstructured partition@?

**Comment by qued** [comment]
For 1. yes, that's the default way forward. 2. would require a code change but as long as it didn't introduce a non-compatible dependency, that would work.

**Comment by l4b4r4b4b4** [comment]
@qued ok will try that out with an env variable.

**Comment by l4b4r4b4b4** [comment]
New [PR](https://github.com/Unstructured-IO/unstructured/pull/2044) adding paddle ocr version as env variable to docker file with default value `PP-OCRv4` and passing it to PaddleOCR function calls.

**Pull request closed without merging**
