### PR TITLE
feat: configure googlevision api endpoint

### PR DESCRIPTION
**Pull request by dlozeve**
The Google Vision API allows for [configuration of the API endpoint](https://cloud.google.com/vision/docs/ocr#regionalization), to select if the data should be sent to the US or the EU. This PR adds an environment variable (`GOOGLEVISION_API_ENDPOINT`) to configure it.

### CODE REVIEW

**Review by christinestraub — APPROVED** [review]
LGTM!

**Review by MthwRobinson — APPROVED** [review]

**Review by MthwRobinson — CHANGES_REQUESTED** [review]
Could you add an entry to the CHANGELOG for this? Otherwise looks good!

**Comment by MthwRobinson** [comment]
Thanks @dlozeve  ! Getting this merged into a feature branch so CI can run, and will get it merged into main from there.

**Comment by MthwRobinson** [comment]
See #3126

**Pull request merged**
