### PR TITLE
default to None for languages <- Ingest test fixtures update

### PR DESCRIPTION
**Pull request by ryannikolaidis**
This pull request includes updated ingest test fixtures.
Please review and merge if appropriate.

### CODE REVIEW

**Comment by Coniferish** [comment]
@rbiseck3 
in `test_unstructured_ingest/test-ingest-local-single-file.sh` where `PYTHONPATH` is being defined, this part below is defining kwargs for `partition()` (so it would be something like `partition(filename, ocr-languages="ind+est", strategy="ocr_only")`) or is it defining the expected output?
```
    --ocr-languages ind+est \
    --strategy ocr_only \
```

When I run `partition(filename="example-docs/language-docs/UDHR_first_article_all.txt", ocr_languages='ind+est', strategy='ocr_only')`, I get this:
```
(Pdb) [print(i, element.metadata.languages) for i, element in enumerate(elements[:20])]
0 ['eng']
1 ['eng']
2 ['eng']
3 ['deu', 'fra']
4 ['eng']
5 ['zho']
6 ['eng', 'swa']
7 ['deu', 'eng', 'cym', 'ind']
8 ['cat', 'fra', 'ron', 'som']
9 ['ind', 'swa']
10 ['ind', 'swa']
11 ['eng', 'som', 'cat']
12 ['kor']
13 ['rus']
14 ['ind']
15 ['swa', 'ind']
16 ['ind']
17 ['rus']
18 ['est', 'som', 'ind']
19 ['afr']
```

I'm confused how all the languages are getting removed in this ingest PR when my changes work for me this way.

**Comment by Coniferish** [comment]
I'm also realizing I overlooked the fact that this document (`UDHR_first_article_all.txt`) should always detect the language per element--there's logic in lang.py to automatically switch from document-level detection to element-level detection if more than one language is detected.

**Comment by rbiseck3** [comment]
@Coniferish, this is the exact partition kwargs being used when the partition function is being called from the `test-ingest-local-single-file.sh` script: 
```
{
  "strategy": "ocr_only",
  "encoding": null,
  "pdf_infer_table_structure": false,
  "languages": [
    "ind",
    "est"
  ]
}
```

**Comment by Coniferish** [comment]
@rbiseck3 
This is what I'm running and getting...
```
>>> from unstructured.partition.auto import partition
>>> filename = "example-docs/language-docs/UDHR_first_article_all.txt"
>>> elements = partition(filename, strategy='ocr_only', pdf_infer_table_structure=False, languages=["ind","est"])
>>> langs = {element.metadata.languages[0] for element in elements if element.metadata.languages}
>>> langs
{'swe', 'tur', 'kor', 'ben', 'swa', 'kan', 'mar', 'mkd', 'urd', 'rus', 'vie', 'som', 'fin', 'ita', 'deu', 'fas', 'jpn', 'spa', 'afr', 'dan', 'est', 'guj', 'slv', 'ces', 'nor', 'cat', 'fra', 'lit', 'tha', 'tgl', 'por', 'ell', 'nep', 'hrv', 'zho', 'heb', 'ara', 'nld', 'sqi', 'ind', 'ukr', 'hun', 'bul', 'hin', 'lav', 'pan', 'ron', 'pol', 'cym', 'eng', 'tel', 'tam', 'slk', 'mal'}
```
Any ideas why the ingest would be different?

**Comment by Coniferish** [comment]
@rbiseck3 Okay... now I see. Thanks for confirming that. All these changes are removing the languages because langdetect can't figure out what language being passed in is--I was only thinking about `languages` being `None` when there was no text and forgetting about if `langdetect` can't figure out the language.

**Pull request merged**
