### PR TITLE
Added Argilla support for standard partitions with `FeedbackDataset`

### LINKED ISSUE #1171: feat/add-argilla-feedbackdataset-staging-brick
**Is your feature request related to a problem? Please describe.**
We are slowly moving all of our tasks to our ‘FeedbackDataset’, which would allow us to create a fully configurable data collection process.
I think it makes sense to create configurable Staging Bricks for
https://docs.argilla.io/en/latest/guides/llms/practical_guides/create_dataset.html#define-record-fields
and  potentially
https://docs.argilla.io/en/latest/guides/llms/practical_guides/create_dataset.html#define-questions
After having set up a Dataset, we can then have a relevant section for a PDF file directly into that dataset by using the staging bricks.

**Describe the solution you'd like**
```python
import argilla as rg
import json

from unstructured.documents.elements import Title, NarrativeText
from unstructured.staging.argilla import stage_for_argilla, argilla_element_converter

elements = [Title(text="Title"), NarrativeText(text="Narrative")]
metadata = [{"type": "title"}, {"type": "text"}]

dataset = rg.FeedbackDataset(
    guidelines="Please, read the question carefully and try to answer it as accurately as possible.",
    fields=[
        rg.TextField(name="title"),
        rg.TextField(name="narrative"),
    ],
    questions=[
        rg.LabelQuestion(
            name="classify_title",
            values=["a", "b"],
        ),
        rg.MultiLabelQuestion(
            name="classify_text",
            values=["a", "b"],
        ),
        rg.TextQuestion(
            name="answer_correction",
            required=False,
        ),
    ]
)

element = argilla_element_converter(elements[0], field="title")
element = argilla_element_converter(elements[1], field="narrative")  

argilla_dataset = stage_for_argilla(elements, "text_classification", metadata=metadata)
```

**Describe alternatives you've considered**
N.A.

**Additional context**
Maybe you know an interesting applied use case that we might be able to cover in a tutorial as a showcase of the new integration.
@jackretterer Ideally, I also want to see an example added [here](https://unstructured-io.github.io/unstructured/examples.html#).

### PR DESCRIPTION
**Pull request by davidberenstein1957**
Closes #1171 

Added support for partition of single-page/element partitions using a pre-defined field-set in Argilla `FeedbackDataset`.
```python
PARTITION_DATASET_FIELDS = {
    # DEFAULT
    "defaults": [ # TODO: do we want to include defaults?
        TextField(name="filename", use_markdown=True),
        TextField(name="last_modified", use_markdown=True),
        TextField(name="filetype", use_markdown=True),
    ],
    # EMAIL
    ARGILLA_PARTITION_TYPES.MSG: [
        TextField(name="sent_from", use_markdown=True),
        TextField(name="sent_to", use_markdown=True),
        TextField(name="subject", use_markdown=True),
        TextField(name="text", use_markdown=True),
        TextField(name="text_with_sep", use_markdown=True)
    ],
    ARGILLA_PARTITION_TYPES.EML: [
        TextField(name="sent_from", use_markdown=True),
        TextField(name="sent_to", use_markdown=True),
        TextField(name="subject", use_markdown=True),
        TextField(name="text", use_markdown=True),
        TextField(name="text_with_sep", use_markdown=True)
    ],
    # TABLES
    # TODO: do we want to correction questions for tables?
    ARGILLA_PARTITION_TYPES.CSV: [
        TextField(name="table", use_markdown=True),
        TextField(name="raw_csv", use_markdown=True),
    ],
    ARGILLA_PARTITION_TYPES.TSV: [
        TextField(name="table", use_markdown=True),
        TextField(name="raw_csv", use_markdown=True),
    ],
    ARGILLA_PARTITION_TYPES.XLSX: [
        TextField(name="page_name", use_markdown=True),
        TextField(name="table", use_markdown=True),
    ],
    ARGILLA_PARTITION_TYPES.XLS: [
        TextField(name="page_name", use_markdown=True),
        TextField(name="table", use_markdown=True),
    ],
    # SLIDES
    ARGILLA_PARTITION_TYPES.PPT: [
        TextField(name="page_number", use_markdown=True),
        TextField(name="title", use_markdown=True, required=False),
        TextField(name="content", use_markdown=True, required=False),
    ],
    ARGILLA_PARTITION_TYPES.PPTX: [
        TextField(name="page_number", use_markdown=True),
        TextField(name="title", use_markdown=True, required=False),
        TextField(name="content", use_markdown=True, required=False),
    ],
    # TEXT
    ARGILLA_PARTITION_TYPES.HTML: [
        TextField(name="head", use_markdown=True),
        TextField(name="body", use_markdown=True),
        TextField(name="scripts", use_markdown=True),
    ]
}
```

Discussion points:
- how will we represent freeform text partitions
    - with pages like `PDF` and `WORD`
    - without pages like `TXT` and `RTF`
    - with DOM like `HTML`
I can see them being automatically unwrapped over new records on a paragraph or page level.
- Do we want to include DEFAULT Fields for every partition type
```python
    # DEFAULT
    "defaults": [ # TODO: do we want to include defaults?
        TextField(name="filename", use_markdown=True),
        TextField(name="last_modified", use_markdown=True),
        TextField(name="filetype", use_markdown=True),
    ],
```
- Do we want to include  DEFAULT Questions? I can see a default Question for `CSV` being for example a request to correct the CSV, but I am unsure about the normal usage of each partition type.
- Can MSG and EML types contain multiple emails?
- How do we want to resolve potentially mixed `partition_multiple_via_api`, and `partition_via_api`?

### CODE REVIEW

**Comment by davidberenstein1957** [comment]
Example Argilla UI MSG/EML
image
Example Argilla UI TSV/CSV
image
Example Argilla UI PPT
image
Example Argilla UI XLSX
image

**Comment by qued** [comment]
Hi @davidberenstein1957 , I've been tracking this PR. I just want to verify that this is still in draft because it's not ready yet, correct?

**Comment by davidberenstein1957** [comment]
@qued it is still in draft. 
But I have been asking for some input from your side. Shown below. Also, I am not sure how 

> Discussion points:
> - how will we represent freeform text partitions
>     - with pages like `PDF` and `WORD`
>     - without pages like `TXT` and `RTF`
>     - with DOM like `HTML` and `XML`
> I can see them being automatically unwrapped over new records on a paragraph or page level.
> - Do we want to include DEFAULT Fields for every partition type
> ```python
>     # DEFAULT
>     "defaults": [ 
>         TextField(name="filename", use_markdown=True),
>         TextField(name="last_modified", use_markdown=True),
>         TextField(name="filetype", use_markdown=True),
>     ],
> ```
> - Do we want to include  DEFAULT Questions? I can see a default Question for `CSV` being for example a request to correct the CSV, but I am unsure about the normal usage of each partition type.
> - Can MSG and EML types contain multiple emails?
> - How do we want to resolve potentially mixed `partition_multiple_via_api`, and `partition_via_api`? => all to another dataset?
Do we want to include metadata to each record?

**Comment by davidberenstein1957** [comment]
@qued I took some decisions and if approved, I will work on some docs.

**Comment by MthwRobinson** [comment]
Closing this PR since it's been a while.

**Pull request closed without merging**
