### PR TITLE
Skip failing posix_path test on Windows

### PR DESCRIPTION
**Pull request by tomaarsen**
Hello!

## Pull Request overview
* Skip failing posix_path test on Windows.

## Details
See https://github.com/Unstructured-IO/unstructured/issues/234#issuecomment-1445026548 for details. 
In short, the following test fails on Windows:
https://github.com/Unstructured-IO/unstructured/blob/a79b365ab47856b891dd77363ade95ccb76ec2f4/test_unstructured/staging/test_base_staging.py#L82-L90
```
FAILED test_unstructured/staging/test_base_staging.py::test_convert_to_isd_serializes_with_posix_paths - NotImplementedError: cannot instantiate 'PosixPath' on your system
```
I've added a [`platform.system()`](https://docs.python.org/3/library/platform.html#platform.system) conditional to skip this test.

## Note
I've again not updated the CHANGELOG. I primarily see user-facing changes there, so I'm not sure if a test suite fix should result in me updating that file. Let me know!

- Tom Aarsen

### CODE REVIEW

**Review by cragwolfe — APPROVED** [review]
LGTM!

**Comment by cragwolfe** [comment]
@tomaarsen , just need to "Update branch" and this is good to go. Since this change is only in a test directory, it evaded the CHANGELOG check, which is good.

**Comment by tomaarsen** [comment]
Very impressive test coverage, by the way!

**Comment by cragwolfe** [comment]
> Very impressive test coverage, by the way!

Thank you! 😁

**Pull request merged**
