### PR TITLE
Kravetsmic/1004 add the ability to ignore <header> and <footer> tags in partition html

### PR DESCRIPTION
**Pull request by kravetsmic**
### Summary 
Added `skip_footers_and_headers` parameter to `partition_html` function

If `skip_footers_and_headers` is True, <header> and <footer> with not be included in the result

Bump to 0.8.9

-----
Close issue #1004

### CODE REVIEW

**Comment by MthwRobinson** [comment]
Per comment on #1008, please address the comments on your other PRs and get them wrapped before we review this one.

**Comment by kravetsmic** [comment]
> Per comment on #1008, please address the comments on your other PRs and get them wrapped before we review this one.

Sure, but could you please check my comments on that PRs (#947 #963 ), I have some questions. @MthwRobinson

**Review by MthwRobinson — APPROVED** [review]
LGTM once CI is passing

**Comment by huangpan2507** [comment]
Does partition_pdf function added skip_footers_and_headers parameter ?  
My unstructured version is  
>root@dell-PowerEdge-R750:/mnt/AI/gen_db# pip show unstructured
>Name: unstructured
>Version: 0.14.6
>Summary: A library that prepares raw documents for downstream ML tasks.
>Home-page: https://github.com/Unstructured-IO/unstructured
>Author: Unstructured Technologies
>Author-email: devops@unstructuredai.io
>License: Apache-2.0
>Location: /opt/conda/envs/hrbot/lib/python3.12/site-packages
>Requires: backoff, beautifulsoup4, chardet, dataclasses-json, emoji, filetype, langdetect, >lxml, nltk, numpy, python-iso639, python-magic, rapidfuzz, requests, tabulate, tqdm, >typing-extensions, unstructured-client, wrapt
>Required-by:

**Pull request merged**
