### PR TITLE
#3447: Rebrand Astra to Astra DB

### PR DESCRIPTION
**Pull request by erichare**
Sorry that this is a very annoying PR @potter-potter - but i've been asked to always keep consistent the references to Astra, to instead be Astra DB. I tried to carefully go through all instances, and i have a corresponding docs PR up here: https://github.com/Unstructured-IO/docs/pull/136

Let me know if you have any questions or if i've missed anything important here.

### CODE REVIEW

**Comment by potter-potter** [comment]
@erichare no worries. Branding is important especially for nerds. :) Will look at it this afternoon.

**Comment by erichare** [comment]
> @erichare no worries. Branding is important especially for nerds. :) Will look at it this afternoon.

So true lol. Much appreciated :) i think the docs PR got merged in so would be great to have this (i had intended that it not be merged until this one was completed, lol, but i didn't make that clear enough). I'm hoping i didnt miss anything here

**Comment by potter-potter** [comment]
https://github.com/Unstructured-IO/unstructured/pull/3458/files

I'll get this merged in soon.

Unfortunately we'll have to do the same here:

https://github.com/Unstructured-IO/unstructured-ingest

Since we are moving the connectors out of the main repo very soon. :)

**Comment by potter-potter** [comment]
@erichare This was merged.
https://github.com/Unstructured-IO/unstructured/commit/59ec64235bcedb5311e64996800601242b7f5989

When you have a chance can you do the same in 

https://github.com/Unstructured-IO/unstructured-ingest

**Comment by erichare** [comment]
Hey @potter-potter sorry about the delay, i'm out this week but yep i'll make the updates to the other repo asap and let you know. Appreciate you and everyone that got this update merged in so quickly!

**Pull request closed without merging**
