### PR TITLE
🐛 fixed emoji xlsx bug

### PR DESCRIPTION
**Pull request by hynky1999**
The xlsx loader is failing when the document contains emojis.
E. g. `!\n\nThanks 🙌🔥🤠`
[WIP] I will add test for this case
See https://github.com/Donohue/medium-to-jekyll/issues/3

### CODE REVIEW

**Comment by MthwRobinson** [comment]
@hynky1999 - Thanks for this! Could you add a small unit test for this and changelog entry? Otherwise looks good to me.

**Review by MthwRobinson — APPROVED** [review]
LGTM - thanks!

**Comment by hynky1999** [comment]
@MthwRobinson Thanks for the help!
I added unit test for testing the emoji extracting and corrected the dependency check.

**Review by MthwRobinson — APPROVED** [review]

**Comment by MthwRobinson** [comment]
@cragwolfe - I think you added this test, can you think of any reason why it would be failing in the docker tests but not in the unit tests?

https://github.com/Unstructured-IO/unstructured/blob/f4ddf535905586115f2a4773cf68870d8e84aaf9/test_unstructured/partition/test_auto.py#L774-L782

**Pull request merged**
