### PR TITLE
update .pre-commit-config to match linting used by CI

### LINKED ISSUE #1905: bug/ pre-commit hook out of date with pyproject.toml
**Describe the bug**
`.pre-commit-config.yaml` does not match `pyproject.toml`, which causes unnecessary/undesirable formatting changes. These changes are not required by CI, so they should not have to be made.

**To Reproduce**
Install pre-commit configuration as described [here](https://github.com/Unstructured-IO/unstructured#installation-instructions-for-local-development). Make a commit and something like the following will be logged:
```
check for added large files..............................................Passed
check toml...........................................(no files to check)Skipped
check yaml...........................................(no files to check)Skipped
check json...........................................(no files to check)Skipped
check xml............................................(no files to check)Skipped
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
mixed line ending........................................................Passed
black....................................................................Passed
ruff.....................................................................Failed
- hook id: ruff
- files were modified by this hook
```

### PR DESCRIPTION
**Pull request by Coniferish**
Closes #1905 
.pre-commit-config.yaml does not match pyproject.toml, which causes unnecessary/undesirable formatting changes. These changes are not required by CI, so they should not have to be made.

**To Reproduce**
Install pre-commit configuration as described [here](https://github.com/Unstructured-IO/unstructured#installation-instructions-for-local-development). Make a commit and something like the following will be logged:
```
check for added large files..............................................Passed
check toml...........................................(no files to check)Skipped
check yaml...........................................(no files to check)Skipped
check json...........................................(no files to check)Skipped
check xml............................................(no files to check)Skipped
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
mixed line ending........................................................Passed
black....................................................................Passed
ruff.....................................................................Failed
- hook id: ruff
- files were modified by this hook
```

### CODE REVIEW

**Review by scanny — APPROVED** [review]
LGTM :)

**Comment by Coniferish** [comment]
@scanny Though the initial trailing commas aren't registering as an issue, I am getting the following commas added (these are new):
```
@@ -764,8 +764,8 @@ class Describe_TextSectionBuilder:
         builder.add_element(
             Text(
                 "Lorem ipsum dolor sit amet consectetur adipiscing elit. In rhoncus ipsum sed"
-                "lectus porta volutpat."
-            )
+                "lectus porta volutpat.",
+            ),
         )
 
         section = next(builder.flush())
```

**Comment by scanny** [comment]
@Coniferish hmm, that's odd, let me take a look. Are those being added locally by the pre-commit hook?

Those aren't by themselves problematic because they don't increase the line count, but they don't happen on my machine and CI doesn't complain about it. Can you tell if those are added by `ruff` or perhaps by `Black`?

**Comment by scanny** [comment]
That looks like `flake-commas: C812`. which should be ignored now. If you take those out and save, do they come back on commit locally? Could have been left-overs I'm thinking.

**Comment by qued** [comment]
Could you also add the ignores to the `make tidy` target in `Makefile`?

**Comment by Coniferish** [comment]
> Could have been left-overs I'm thinking.

Yah, looks like they were. My mistake.

**Pull request merged**
