### PR TITLE
chore[ingest]: fix confluence ingest diff tests

### PR DESCRIPTION
**Pull request by ahmetmeleq**
**Describe the bug**
Confluence ingest tests are not consistent between different runs, and can even be inconsistent between different jobs (3.8 / 3.9 / 3.10 / 3.11) within the same run. This causes ingest test fixtures to not hold in certain cases.

**To Reproduce**
We don't know how to (except that we know this occurs in CI runs for PRs). We've tried to reproduce the issue [via running CI several times](https://github.com/Unstructured-IO/unstructured/pull/1082), however we could not reproduce it. 

Here are examples of this issue happening:

- [test_ingest 3.9 fail, test_ingest 3.11 pass](https://github.com/Unstructured-IO/unstructured/actions/runs/5582771117) (pr: feat: confluence connector (cloud)) 
- [test_ingest 3.8 fail, test_ingest 3.11 and 3.10 pass](https://github.com/Unstructured-IO/unstructured/actions/runs/5802436825) (pr: Chore[ingest]: adding parameter --partition-pdf-infer-table-structure)
- [test_ingest 3.10 fail](https://github.com/Unstructured-IO/unstructured/actions/runs/5813927185) (pr: feat: Sharepoint connector)

What we know:
- We know that it’s not tied to a particular python version, different versions can fail or pass without consistency
- We know that a failed run / job can pass right when we rerun it

**Expected behavior**

- At least one of the CI / test_ingest jobs failing on the confluence connector step, 
- and,
  - the same job passing when the CI is rerun - without a change in code
  - (optional) a different test_ingest job (3.8 , 3.9 , 3.10 , 3.11) passing in the very same run that one test_ingest job failed

### CODE REVIEW

**Review by ryannikolaidis — APPROVED** [review]
lgtm! worth adding the details from your findings in the PR description. let's hope this does the trick 🤞

**Comment by ahmetmeleq** [comment]
Edited first message with first findings, adding later findings down below ✅

**Comment by ahmetmeleq** [comment]
> lgtm! worth adding the details from your findings in the PR description. let's hope this does the trick 🤞

Edited first message with first findings, adding later findings down below ✅

**Comment by ahmetmeleq** [comment]
It seems from the examples that this behaviour happens exclusively in “personal spaces” in Confluence, where no additional document is created, and where the default “Home” document of the personal space is fetched. This “Home” document is auto-generated by Confluence.

It might be worth trying to exclude these “Home” documents from the diff test to see if the ingestion other, user-created documents are behaving in a deterministic way. [That is](https://github.com/Unstructured-IO/unstructured/pull/1082/commits/eea71394a756f4cc6c4c9030725254b24dc58ae1) the approach we’re currently taking in this PR.

**Pull request merged**
